micronaut:
  application:
    name: carrosGrpc
datasources:
  default:
    url: jdbc:mysql://localhost:3306/carros_grpc?useTimezone=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
